//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestBed.Pages
{
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index()
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.Equals(null, resourceMan))
                {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TestBed.Resources.Pages.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static string Welcome
        {
            get
            {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }

        internal static string Learn
        {
            get
            {
                return ResourceManager.GetString("Learn", resourceCulture);
            }
        }

        internal static string IndexTitle
        {
            get
            {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }

        internal static string Submit
        {
            get
            {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }

        // Нови колони
        internal static string Medallion
        {
            get
            {
                return ResourceManager.GetString("Medallion", resourceCulture);
            }
        }

        internal static string HashLicense
        {
            get
            {
                return ResourceManager.GetString("HashLicense", resourceCulture);
            }
        }

        internal static string PickupTime
        {
            get
            {
                return ResourceManager.GetString("PickupTime", resourceCulture);
            }
        }

        internal static string DropOffTime
        {
            get
            {
                return ResourceManager.GetString("DropOffTime", resourceCulture);
            }
        }

        internal static string Duration
        {
            get
            {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }

        internal static string Distance
        {
            get
            {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }

        internal static string PLon
        {
            get
            {
                return ResourceManager.GetString("PLon", resourceCulture);
            }
        }

        internal static string PLat
        {
            get
            {
                return ResourceManager.GetString("PLat", resourceCulture);
            }
        }

        internal static string DLon
        {
            get
            {
                return ResourceManager.GetString("DLon", resourceCulture);
            }
        }

        internal static string DLat
        {
            get
            {
                return ResourceManager.GetString("DLat", resourceCulture);
            }
        }

        internal static string PaymentType
        {
            get
            {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }

        internal static string FareAmount
        {
            get
            {
                return ResourceManager.GetString("FareAmount", resourceCulture);
            }
        }

        internal static string Surcharge
        {
            get
            {
                return ResourceManager.GetString("Surcharge", resourceCulture);
            }
        }

        internal static string Tax
        {
            get
            {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }

        internal static string TipAmount
        {
            get
            {
                return ResourceManager.GetString("TipAmount", resourceCulture);
            }
        }

        internal static string TollsAmount
        {
            get
            {
                return ResourceManager.GetString("TollsAmount", resourceCulture);
            }
        }

        internal static string TotalAmount
        {
            get
            {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
    }
}
